"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Download, TrendingUp, Users, Calendar, AlertTriangle } from "lucide-react"

interface ReportsProps {
  onBack: () => void
}

export function Reports({ onBack }: ReportsProps) {
  const reportData = {
    totalMothers: 245,
    pregnantWomen: 89,
    lactatingMothers: 156,
    highRiskCases: 8,
    thisMonthDeliveries: 23,
    vaccinations: 234,
    healthyPregnancies: 94,
    breastfeedingSuccess: 87,
  }

  const monthlyStats = [
    { month: "Jan", pregnant: 82, lactating: 148, deliveries: 18 },
    { month: "Feb", pregnant: 85, lactating: 152, deliveries: 21 },
    { month: "Mar", pregnant: 89, lactating: 156, deliveries: 23 },
  ]

  const exportReport = () => {
    const reportContent = `MATERNAL HEALTH REPORT
======================
Generated on: ${new Date().toLocaleDateString()}

KEY METRICS
-----------
Total Mothers: ${reportData.totalMothers}
Pregnant Women: ${reportData.pregnantWomen}
Lactating Mothers: ${reportData.lactatingMothers}
High-Risk Cases: ${reportData.highRiskCases}
Deliveries This Month: ${reportData.thisMonthDeliveries}
Healthy Pregnancies: ${reportData.healthyPregnancies}%

MONTHLY TRENDS
--------------
${monthlyStats.map(stat => `${stat.month} 2024: ${stat.pregnant} pregnant, ${stat.lactating} lactating, ${stat.deliveries} deliveries`).join('\n')}

PREGNANCY OUTCOMES
------------------
Normal deliveries: 92%
C-section deliveries: 8%
Average birth weight: 2.8kg
Complications: 3%

BREASTFEEDING SUCCESS
--------------------
Exclusive breastfeeding: 78%
Mixed feeding: 19%
Formula only: 3%
6-month continuation: 87%

KEY PERFORMANCE INDICATORS
--------------------------
Antenatal Coverage: 96% (Target: 95%)
Skilled Birth Attendance: 89% (Target: 85%)
Postnatal Care: 94% (Target: 90%)
Family Planning: 91% (Target: 80%)

---
Report generated by C4H Healthcare EMR System`

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `maternal-health-report-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <Button variant="ghost" size="icon" onClick={onBack}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Health Reports</h1>
            <p className="text-gray-600">Maternal health analytics and insights</p>
          </div>
        </div>
        <Button className="bg-pink-600 hover:bg-pink-700" onClick={exportReport}>
          <Download className="h-4 w-4 mr-2" />
          Export Report
        </Button>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
        <div className="health-card p-4 sm:p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-2xl bg-gradient-to-br from-pink-100 to-purple-100">
              <Users className="h-6 w-6 text-pink-800" />
            </div>
            <TrendingUp className="h-5 w-5 text-green-500" />
          </div>
          <div>
            <p className="text-3xl font-bold text-slate-900 mb-1">{reportData.totalMothers}</p>
            <p className="text-sm font-medium text-slate-600 mb-2">Total Mothers</p>
            <p className="text-xs text-green-600">+12% this month</p>
          </div>
        </div>

        <div className="health-card p-4 sm:p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-2xl bg-gradient-to-br from-purple-100 to-blue-100">
              <Calendar className="h-6 w-6 text-purple-600" />
            </div>
            <TrendingUp className="h-5 w-5 text-green-500" />
          </div>
          <div>
            <p className="text-3xl font-bold text-slate-900 mb-1">{reportData.thisMonthDeliveries}</p>
            <p className="text-sm font-medium text-slate-600 mb-2">Deliveries This Month</p>
            <p className="text-xs text-green-600">+9% from last month</p>
          </div>
        </div>

        <div className="health-card p-4 sm:p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-2xl bg-gradient-to-br from-green-100 to-emerald-100">
              <TrendingUp className="h-6 w-6 text-green-600" />
            </div>
          </div>
          <div>
            <p className="text-3xl font-bold text-slate-900 mb-1">{reportData.healthyPregnancies}%</p>
            <p className="text-sm font-medium text-slate-600 mb-2">Healthy Pregnancies</p>
            <p className="text-xs text-green-600">Above target (90%)</p>
          </div>
        </div>

        <div className="health-card p-4 sm:p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-2xl bg-gradient-to-br from-red-100 to-pink-100">
              <AlertTriangle className="h-6 w-6 text-red-600" />
            </div>
          </div>
          <div>
            <p className="text-3xl font-bold text-slate-900 mb-1">{reportData.highRiskCases}</p>
            <p className="text-sm font-medium text-slate-600 mb-2">High-Risk Cases</p>
            <p className="text-xs text-red-600">Requires attention</p>
          </div>
        </div>
      </div>

      {/* Monthly Trends */}
      <div className="health-card p-4 sm:p-6">
        <h2 className="text-xl font-bold text-slate-900 mb-6">Monthly Trends</h2>
        <div className="space-y-4">
          {monthlyStats.map((stat, index) => (
            <div key={stat.month} className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl">
              <div className="font-semibold text-slate-900">{stat.month} 2024</div>
              <div className="flex space-x-4 sm:space-x-6 text-sm">
                <div className="text-center">
                  <div className="text-lg font-bold text-pink-800">{stat.pregnant}</div>
                  <div className="text-slate-600">Pregnant</div>
                </div>
                <div className="text-center">
                  <div className="text-lg font-bold text-purple-600">{stat.lactating}</div>
                  <div className="text-slate-600">Lactating</div>
                </div>
                <div className="text-center">
                  <div className="text-lg font-bold text-blue-600">{stat.deliveries}</div>
                  <div className="text-slate-600">Deliveries</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Health Outcomes */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="health-card p-4 sm:p-6">
          <h2 className="text-xl font-bold text-slate-900 mb-6">Pregnancy Outcomes</h2>
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Normal deliveries</span>
              <span className="font-bold text-green-600">92%</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">C-section deliveries</span>
              <span className="font-bold text-orange-600">8%</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Average birth weight</span>
              <span className="font-bold text-blue-600">2.8kg</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Complications</span>
              <span className="font-bold text-red-600">3%</span>
            </div>
          </div>
        </div>

        <div className="health-card p-4 sm:p-6">
          <h2 className="text-xl font-bold text-slate-900 mb-6">Breastfeeding Success</h2>
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Exclusive breastfeeding</span>
              <span className="font-bold text-green-600">78%</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Mixed feeding</span>
              <span className="font-bold text-orange-600">19%</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Formula only</span>
              <span className="font-bold text-red-600">3%</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">6-month continuation</span>
              <span className="font-bold text-blue-600">67%</span>
            </div>
          </div>
        </div>
      </div>

      {/* Performance Indicators */}
      <div className="health-card p-4 sm:p-6">
        <h2 className="text-xl font-bold text-slate-900 mb-6">Key Performance Indicators</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 sm:gap-6">
          <div className="text-center p-4 bg-blue-50 rounded-2xl">
            <div className="text-2xl font-bold text-blue-600">96%</div>
            <div className="text-sm text-slate-600 mt-1">Antenatal Coverage</div>
            <div className="text-xs text-slate-500">Target: 95%</div>
          </div>
          <div className="text-center p-4 bg-green-50 rounded-2xl">
            <div className="text-2xl font-bold text-green-600">89%</div>
            <div className="text-sm text-slate-600 mt-1">Skilled Birth Attendance</div>
            <div className="text-xs text-slate-500">Target: 85%</div>
          </div>
          <div className="text-center p-4 bg-purple-50 rounded-2xl">
            <div className="text-2xl font-bold text-purple-600">94%</div>
            <div className="text-sm text-slate-600 mt-1">Postnatal Care</div>
            <div className="text-xs text-slate-500">Target: 90%</div>
          </div>
          <div className="text-center p-4 bg-pink-50 rounded-2xl">
            <div className="text-2xl font-bold text-pink-600">91%</div>
            <div className="text-sm text-slate-600 mt-1">Family Planning</div>
            <div className="text-xs text-slate-500">Target: 85%</div>
          </div>
        </div>
      </div>
    </div>
  )
}
