"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Download, TrendingUp, Users, Calendar, AlertTriangle } from "lucide-react"

interface ReportsProps {
  onBack: () => void
}

export function Reports({ onBack }: ReportsProps) {
  const reportData = {
    totalMothers: 245,
    pregnantWomen: 89,
    lactatingMothers: 156,
    highRiskCases: 8,
    thisMonthDeliveries: 23,
    vaccinations: 234,
    healthyPregnancies: 94,
    breastfeedingSuccess: 87,
  }

  const monthlyStats = [
    { month: "Jan", pregnant: 82, lactating: 148, deliveries: 18 },
    { month: "Feb", pregnant: 85, lactating: 152, deliveries: 21 },
    { month: "Mar", pregnant: 89, lactating: 156, deliveries: 23 },
  ]

  const exportReport = () => {
    const reportContent = `MATERNAL HEALTH REPORT
======================
Generated on: ${new Date().toLocaleDateString()}

KEY METRICS
-----------
Total Mothers: ${reportData.totalMothers}
Pregnant Women: ${reportData.pregnantWomen}
Lactating Mothers: ${reportData.lactatingMothers}
High-Risk Cases: ${reportData.highRiskCases}
Deliveries This Month: ${reportData.thisMonthDeliveries}
Healthy Pregnancies: ${reportData.healthyPregnancies}%

MONTHLY TRENDS
--------------
${monthlyStats.map(stat => `${stat.month} 2024: ${stat.pregnant} pregnant, ${stat.lactating} lactating, ${stat.deliveries} deliveries`).join('\n')}

PREGNANCY OUTCOMES
------------------
Normal deliveries: 92%
C-section deliveries: 8%
Average birth weight: 2.8kg
Complications: 3%

BREASTFEEDING SUCCESS
--------------------
Exclusive breastfeeding: 78%
Mixed feeding: 19%
Formula only: 3%
6-month continuation: 87%

KEY PERFORMANCE INDICATORS
--------------------------
Antenatal Coverage: 96% (Target: 95%)
Skilled Birth Attendance: 89% (Target: 85%)
Postnatal Care: 94% (Target: 90%)
Family Planning: 91% (Target: 80%)

---
Report generated by C4H Healthcare EMR System`

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `maternal-health-report-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <Button variant="ghost" size="icon" onClick={onBack}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Health Reports</h1>
            <p className="text-gray-600">Maternal health analytics and insights</p>
          </div>
        </div>
        <Button className="bg-pink-600 hover:bg-pink-700" onClick={exportReport}>
          <Download className="h-4 w-4 mr-2" />
          Export Report
        </Button>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div className="p-2 rounded-lg bg-pink-50">
                  <Users className="h-5 w-5 text-pink-800" />
              </div>
              <TrendingUp className="h-4 w-4 text-green-500" />
            </div>
            <div className="mt-3">
              <p className="text-2xl font-bold text-gray-900">{reportData.totalMothers}</p>
              <p className="text-sm font-medium text-gray-600">Total Mothers</p>
              <p className="text-xs text-green-600 mt-1">+12% this month</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div className="p-2 rounded-lg bg-purple-50">
                <Calendar className="h-5 w-5 text-purple-600" />
              </div>
              <TrendingUp className="h-4 w-4 text-green-500" />
            </div>
            <div className="mt-3">
              <p className="text-2xl font-bold text-gray-900">{reportData.thisMonthDeliveries}</p>
              <p className="text-sm font-medium text-gray-600">Deliveries This Month</p>
              <p className="text-xs text-green-600 mt-1">+9% from last month</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div className="p-2 rounded-lg bg-green-50">
                <TrendingUp className="h-5 w-5 text-green-600" />
              </div>
            </div>
            <div className="mt-3">
              <p className="text-2xl font-bold text-gray-900">{reportData.healthyPregnancies}%</p>
              <p className="text-sm font-medium text-gray-600">Healthy Pregnancies</p>
              <p className="text-xs text-green-600 mt-1">Above target (90%)</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div className="p-2 rounded-lg bg-red-50">
                <AlertTriangle className="h-5 w-5 text-red-600" />
              </div>
            </div>
            <div className="mt-3">
              <p className="text-2xl font-bold text-gray-900">{reportData.highRiskCases}</p>
              <p className="text-sm font-medium text-gray-600">High-Risk Cases</p>
              <p className="text-xs text-red-600 mt-1">Requires attention</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Monthly Trends */}
      <Card className="border-0 shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg font-semibold">Monthly Trends</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {monthlyStats.map((stat, index) => (
              <div key={stat.month} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                <div className="font-medium text-gray-900">{stat.month} 2024</div>
                <div className="flex space-x-6 text-sm">
                  <div className="text-center">
                    <div className="font-bold text-pink-800">{stat.pregnant}</div>
                    <div className="text-gray-600">Pregnant</div>
                  </div>
                  <div className="text-center">
                    <div className="font-bold text-purple-600">{stat.lactating}</div>
                    <div className="text-gray-600">Lactating</div>
                  </div>
                  <div className="text-center">
                    <div className="font-bold text-blue-600">{stat.deliveries}</div>
                    <div className="text-gray-600">Deliveries</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Health Outcomes */}
      <div className="grid lg:grid-cols-2 gap-6">
        <Card className="border-0 shadow-sm">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">Pregnancy Outcomes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <span className="text-gray-600">Normal deliveries</span>
                <span className="font-bold text-green-600">92%</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-600">C-section deliveries</span>
                <span className="font-bold text-blue-600">8%</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-600">Average birth weight</span>
                <span className="font-bold text-gray-900">2.8kg</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-600">Complications</span>
                <span className="font-bold text-red-600">3%</span>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-sm">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">Breastfeeding Success</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <span className="text-gray-600">Exclusive breastfeeding</span>
                <span className="font-bold text-green-600">78%</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-600">Mixed feeding</span>
                <span className="font-bold text-yellow-600">19%</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-600">Formula only</span>
                <span className="font-bold text-red-600">3%</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-600">6-month continuation</span>
                <span className="font-bold text-green-600">87%</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Performance Indicators */}
      <Card className="border-0 shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg font-semibold">Key Performance Indicators</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="text-center p-4 bg-green-50 rounded-lg">
              <div className="text-2xl font-bold text-green-600">96%</div>
              <div className="text-sm text-gray-600">Antenatal Coverage</div>
              <div className="text-xs text-green-600 mt-1">Target: 95%</div>
            </div>
            <div className="text-center p-4 bg-blue-50 rounded-lg">
              <div className="text-2xl font-bold text-blue-600">89%</div>
              <div className="text-sm text-gray-600">Skilled Birth Attendance</div>
              <div className="text-xs text-blue-600 mt-1">Target: 85%</div>
            </div>
            <div className="text-center p-4 bg-purple-50 rounded-lg">
              <div className="text-2xl font-bold text-purple-600">94%</div>
              <div className="text-sm text-gray-600">Postnatal Care</div>
              <div className="text-xs text-purple-600 mt-1">Target: 90%</div>
            </div>
            <div className="text-center p-4 bg-pink-50 rounded-lg">
              <div className="text-2xl font-bold text-pink-800">91%</div>
              <div className="text-sm text-gray-600">Family Planning</div>
              <div className="text-xs text-slate-600 mt-1">Target: 80%</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
